export const containers = {
  do: document.getElementById("do-container"),
  doing: document.getElementById("doing-container"),
  done: document.getElementById("done-container"),
};

export const allMessages = [
  "Amazing! You&rsquo;ve tackled everything on your plate!",
  "Outstanding! Task list cleared like a champ!",
  "Bravo! All tasks have been conquered!",
  "Great job! You&rsquo;ve crossed the finish line!",
  "Fantastic! No more tasks, time to celebrate!",
  "Mission accomplished! What a pro!",
  "You&rsquo;re on fire! Every task is done! 🔥",
  "Boom! All tasks obliterated! 💥",
  "Victory is yours! Nothing left to do! 🏆",
  "Cheers to your productivity! 🍻",
  "Kudos! You&rsquo;re officially task-free!",
  "You&rsquo;ve earned a break&mdash;awesome job! ☕",
  "You&rsquo;re a rockstar! No tasks left behind! 🎸",
  "Legendary performance! All clear! 👑",
  "Amazing effort! Everything is checked off! ✅",
  "Fantastic work! You&rsquo;ve aced it all! 💯",
  "Done and dusted! Time to relax. 🧘",
  "Woohoo! Everything is complete! 🎉",
  "Epic win! Your list is empty! 🚀",
  "Incredible! You&rsquo;ve achieved task-zero!",
  "You&rsquo;re unstoppable! No tasks remain!",
  "Congratulations! You&rsquo;ve mastered productivity! 🧠",
  "What a superstar! Tasks cleared effortlessly.",
  "Impressive! You&rsquo;ve knocked it out of the park! ⚾",
  "All done? You&rsquo;re officially amazing!",
  "Gold medal for productivity goes to you! 🥇",
  "Bravo! Task-free zone achieved!",
  "Excellence at its best! Great job! ⭐",
  "You&rsquo;re a legend! Mission complete.",
  "Smashing success! Your list is history! 📜",
  "Phenomenal! Tasks cleared in style! ✨",
  "Outstanding effort! Nothing left undone.",
  "Mic drop! You&rsquo;ve done it all. 🎤",
  "Unstoppable force! List zero achieved.",
  "You&rsquo;ve crushed it! Every task is history.",
  "Hats off! Your tasks have been obliterated! 🎩",
  "Round of applause! Task-free life achieved. 👏",
  "You&rsquo;re a wizard of productivity! 🧙‍♂️",
  "Perfection achieved! Tasks are gone. 🌟",
  "High five! Your list is history. 🙌",
  "You&rsquo;re the boss! Task-free status unlocked. 💼",
  "Masterclass in productivity! Everything&rsquo;s done.",
  "Zero tasks, 100% success. 📈",
  "Achievement unlocked: Inbox Zero, Board Zero. 🕹️",
  "The task board has been vanquished. ⚔️",
  "Clean slate vibes only. 🧼",
  "You deserve cake. 🍰",
];

export const elements = {
  inputBox: document.getElementById("input-box"),
  taskModal: document.getElementById("taskModal"),
  errorMessage: document.getElementById("error-message"),
  sortOptionsDo: document.getElementById("sort-options-do"),
  sortOptionsDone: document.getElementById("sort-options-done"),
  searchStatus: document.getElementById("search-status"),
  saveModal: document.getElementById("saveModal"),
  cancelModal: document.getElementById("cancelModal"),
  modalTaskName: document.getElementById("modalTaskName"),
  modalTaskDescription: document.getElementById("modalTaskDescription"),
  modalTaskPriority: document.getElementById("modalTaskPriority"),
  modalActivityType: document.getElementById("modalActivityType"),
  modalActivityCustom: document.getElementById("modalActivityCustom"),
  modalRecurrenceType: document.getElementById("modalRecurrenceType"),
  modalRecurrenceDays: document.getElementById("modalRecurrenceDays"),
  modalTaskDueDate: document.getElementById("modalTaskDueDate"),
  modalTaskTags: document.getElementById("modalTaskTags"),
  taskTemplate: document.getElementById("task-template"),
  taskViewSelect: document.getElementById("task-view-options"),
  darkModeToggle: document.getElementById("dark-mode-toggle"),
  darkModeIcon: document.getElementById("moon-icon"),
  closeAllPanelsBtn: document.getElementsByClassName("close-panel"),
  resetBtn: document.getElementById("clearTasksBtn"),
  resetModal: document.getElementById("reset-modal"),
  cancelReset: document.getElementById("cancel-reset"),
  confirmReset: document.getElementById("confirm-reset"),
  simToggle: document.getElementById("sim-toggle"),
  simIcon: document.getElementById("sim-toggle-icon"),
};
